config/routes.rb
Rails.application.routes.draw do
  resources :sneakers
  resources :brands
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :sneakers
  mount_uploader :logo, LogoUploader
end

app/models/sneaker.rb
class Sneaker < ApplicationRecord
  belongs_to :brand
  mount_uploader :image, ImageUploader
  validates :brand_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @sneakers = @brand.sneakers
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name, :logo, :image)
    end
end

app/controllers/sneakers_controller.rb
class SneakersController < ApplicationController
  before_action :set_sneaker, only: [:show, :edit, :update, :destroy]

  # GET /sneakers
  # GET /sneakers.json
  def index
    @sneakers = Sneaker.all
  end

  # GET /sneakers/1
  # GET /sneakers/1.json
  def show
  end

  # GET /sneakers/new
  def new
    @sneaker = Sneaker.new
  end

  # GET /sneakers/1/edit
  def edit
  end

  # POST /sneakers
  # POST /sneakers.json
  def create
    @sneaker = Sneaker.new(sneaker_params)

    respond_to do |format|
      if @sneaker.save
        format.html { redirect_to @sneaker, notice: 'Sneaker was successfully created.' }
        format.json { render :show, status: :created, location: @sneaker }
      else
        format.html { render :new }
        format.json { render json: @sneaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sneakers/1
  # PATCH/PUT /sneakers/1.json
  def update
    respond_to do |format|
      if @sneaker.update(sneaker_params)
        format.html { redirect_to @sneaker, notice: 'Sneaker was successfully updated.' }
        format.json { render :show, status: :ok, location: @sneaker }
      else
        format.html { render :edit }
        format.json { render json: @sneaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sneakers/1
  # DELETE /sneakers/1.json
  def destroy
    @sneaker.destroy
    respond_to do |format|
      format.html { redirect_to sneakers_url, notice: 'Sneaker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sneaker
      @sneaker = Sneaker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sneaker_params
      params.require(:sneaker).permit(:brand_id, :model, :sex, :price, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/sneakers_helper.rb
module SneakersHelper
end

app/views/brands/_form.html.erb
<%= form_for(brand) do |f| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, id: :brand_id %>
  </div>

  <div class="field">
    <%= f.label :logo %>
    <%= f.file_field :logo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Logo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td><%= brand.logo %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @brand.logo %>
</p>

<%= image_tag @brand.logo %>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>

<hr>

<%# render 'sneakers/index' %>

<% @sneakers.each do |sneaker| %>
 <%= render 'sneakers/show', sneaker: sneaker %>
<% end %>

<%= render 'sneakers/form', sneaker: Sneaker.new %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HSESneaker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to 'Brands', brands_url %>
      <%= link_to 'Sneakers', sneakers_url %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/sneakers/_form.html.erb
<%= form_for(sneaker) do |f| %>
  <% if sneaker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sneaker.errors.count, "error") %> prohibited this sneaker from being saved:</h2>

      <ul>
      <% sneaker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @brand %>
  <%= f.hidden_field :brand_id, value: @brand.id %>
  <% else %>
    <div class="field">
      <%= f.label :brand_id %>
      <%#= f.number_field :brand_id %>
      <%= select("sneaker", "brand_id", Brand.all.collect {|b| [ b.name, b.id ] }, { include_blank: true }) %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :sex %>
    <%= f.text_field :sex %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sneakers/_index.html.erb
<h1>Sneakers</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Sex</th>
      <th>Price</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sneakers.each do |sneaker| %>
      <tr>
        <td><%= sneaker.brand_id %></td>
        <td><%= sneaker.model %></td>
        <td><%= sneaker.sex %></td>
        <td><%= sneaker.price %></td>
        <td><%= sneaker.image %></td>
        <td><%= link_to 'Show', sneaker %></td>
        <td><%= link_to 'Edit', edit_sneaker_path(sneaker) %></td>
        <td><%= link_to 'Destroy', sneaker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sneaker', new_sneaker_path %>

app/views/sneakers/_show.html.erb
<h2><%= link_to sneaker.model, sneaker %></h2>

<p>
  <strong>Sex:</strong>
  <%= sneaker.sex %>
</p>

<p>
  <strong>Price:</strong>
  <%= sneaker.price %>
</p>

<p>
  <strong>Image:</strong>
  <%= sneaker.image %>
</p>


<div>
  <%= image_tag sneaker.image %>
</div>

<%= link_to 'Edit', edit_sneaker_path(sneaker) %> |
<%= link_to 'Destroy', sneaker, method: :delete, data: { confirm: 'Are you sure?' } %>

<hr>

app/views/sneakers/edit.html.erb
<h1>Editing Sneaker</h1>

<%= render 'form', sneaker: @sneaker %>

<%= link_to 'Show', @sneaker %> |
<%= link_to 'Back', sneakers_path %>

app/views/sneakers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sneakers</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Sex</th>
      <th>Price</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sneakers.each do |sneaker| %>
      <tr>
        <td><%= sneaker.brand_id %></td>
        <td><%= sneaker.model %></td>
        <td><%= sneaker.sex %></td>
        <td><%= sneaker.price %></td>
        <td><%= sneaker.image %></td>
        <td><%= link_to 'Show', sneaker %></td>
        <td><%= link_to 'Edit', edit_sneaker_path(sneaker) %></td>
        <td><%= link_to 'Destroy', sneaker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sneaker', new_sneaker_path %>

app/views/sneakers/new.html.erb
<h1>New Sneaker</h1>

<%= render 'form', sneaker: @sneaker %>

<%= link_to 'Back', sneakers_path %>

app/views/sneakers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= Brand.find(@sneaker.brand_id).name %>
</p>

<p>
  <strong>Model:</strong>
  <%= @sneaker.model %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @sneaker.sex %>
</p>

<p>
  <strong>Price:</strong>
  <%= @sneaker.price %>
</p>

<p>
  <strong>Image:</strong>
  <%= @sneaker.image %>
</p>

<%= image_tag @sneaker.image %>

<%= link_to 'Edit', edit_sneaker_path(@sneaker) %> |
<%= link_to 'Back', sneakers_path %>